FROM ubuntu:20.04
COPY target/com.ewolff.microservice.bonus.bonusapp /com.ewolff.microservice.bonus.bonusapp
RUN chmod +x /com.ewolff.microservice.bonus.bonusapp
CMD ["/com.ewolff.microservice.bonus.bonusapp"]