name: Build and Publish Native Docker Images for Other Microservices

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-others-native:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build native microservices with Maven
      run: cd microservice-istio-demo && mvn -B spring-boot:build-image --file pom.xml
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image for native microservice order
      run: |
        IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}
        docker tag microservice-istio-order:0.0.1-SNAPSHOT $IMAGE_PREFIX/microservice-istio-order-native:1
        docker push $IMAGE_PREFIX/microservice-istio-order-native:1
    - name: Push image for native microservice invoicing
      run: |
        IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}
        docker tag microservice-istio-invoicing:0.0.1-SNAPSHOT $IMAGE_PREFIX/microservice-istio-invoicing-native:1
        docker push $IMAGE_PREFIX/microservice-istio-invoicing-native:1
    - name: Push image for native microservice shippinginvoicing
      run: |
        IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}
        docker tag microservice-istio-shipping:0.0.1-SNAPSHOT $IMAGE_PREFIX/microservice-istio-shipping-native:1
        docker push $IMAGE_PREFIX/microservice-istio-shipping-native:1